[build]
# default target
target = "wasm32-wasi"

[target.wasm32-wasi]
runner = "./scripts/wasmedge-runner.sh"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1

[package.metadata.docs.rs]
# only build for wasm32-wasi now
targets = ["wasm32-wasi"]
