name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:latest
    steps:
      - uses: actions/checkout@v2

      - name: install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install rust wasm32-wasi
        run: rustup target add wasm32-wasi

      - name: build wasmedge from source with tflite backend
        run: |
          bash -c "\
          export WASMEDGE_PATH=~/.wasmedge;\
          git clone https://github.com/WasmEdge/WasmEdge;\
          cd ./WasmEdge;\
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
          -DWASMEDGE_PLUGIN_WASI_NN_BACKEND=TensorflowLite -DCMAKE_INSTALL_PREFIX=${WASMEDGE_PATH} .;\
          cmake --build build;\
          cmake --install build;\
          cp build/_deps/wasmedgetensorflowdepslite-src/libtensorflowlite_c.so ${WASMEDGE_PATH}/lib/;"

      #      - name: init wasmedge environment
      #        run: ./scripts/wasmedge-init.sh

      - name: test
        run: cargo test --release -- --nocapture
